[versions]

android-plugin = '9.0.0'

android-sdk-compile = '36.1'
android-sdk-min = '26'

androidx-annotation = '1.9.1'
androidx-core = '1.17.0'

java-source = '11'

java-toolchain = '21'

kotlin = { strictly = '2.3.0' } # "strictly" in case AGP is ahead of us

junit = '4.13.2'


[libraries]

androidx-annotation = { module = 'androidx.annotation:annotation', version.ref = 'androidx-annotation' }
androidx-core-ktx = { module = 'androidx.core:core-ktx', version.ref = 'androidx-core' }

bubenheimer-kotlinutil = { module = 'org.bubenheimer:kotlinutil', version = '1.0-SNAPSHOT' }

junit = { module = 'junit:junit', version.ref = 'junit' }

kotlin-test-junit = { module = 'org.jetbrains.kotlin:kotlin-test-junit', version.ref = 'kotlin' }


[plugins]

android-library = { id = 'com.android.library', version.ref = 'android-plugin' }

kotlin-android = { id = 'org.jetbrains.kotlin.android', version.ref = 'kotlin' }
